# Generated by Django 3.2.9 on 2022-02-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_product_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='precio',
        ),
    ]
