# Generated by Django 3.2.9 on 2022-02-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_product_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.FloatField(default=1, null=True),
        ),
    ]
